import { TableCryptos } from "@/components/TableCryptos";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="h-screen">
      <div className="mx-auto h-full flex justify-center items-center max-w-7xl px-4 sm:px-6 lg:px-8">
        <TableCryptos/>
      </div>
    </main>
  );
}

